### ISSUE TITLE
[enhancement] Test message when exception is thrown

### ISSUE THREAD

**Issue by chrismichaels84** [Codeception/Specify#16]
It would be great to be able to:
```php
$this->specify("it throws an exception without a default connection", function () {
   // Do something
}, ['throws' => 'Spider\Exceptions\ConnectionNotFoundException', 'message' => 'The exception message']);
```

And I'm happy to put together a PR if you let me know what syntax/api you would like (ie message, exception message `[throws => ['class', 'message']]` as well as `['throws' => 'class']`

**Comment by DavertMik** [comment]
thanks again!
