### ISSUE TITLE
Specify exhausts available memory

### ISSUE THREAD

**Issue by settermjd** [Codeception/Specify#20]
I've started using Specify and Verify in a new project and find that progressively it exhausts all available memory. Here's a simple class, whose test is called after 4 other tests. 

```php
<?php

namespace App\Entity;

class Name extends Base
{
    protected $first;
    protected $last;

    public function getFirst()
    {
        return $this->first;
    }

    public function getLast()
    {
        return $this->last;
    }
}
```

And here is the test for it:

```php
use \App\Entity\Name;

class NameTest extends \Codeception\TestCase\Test
{
    use \Codeception\Specify;

    protected $tester;
    protected $faker;

    protected function _before()
    {
        $this->faker = Faker\Factory::create();
    }

    protected function _after()
    {
        $this->faker = null;
    }

    public function testCanInstantiateANameObject()
    {
        $properties = [
            'first' => $this->faker->firstName,
            'last' => $this->faker->lastName
        ];
        $name = new Name($properties);
        $this->specify("Can initialize and hydrate a name object", function() use($name, $properties) {
            $this->assertSame($properties['first'], $name->getFirst());
            $this->assertSame($properties['last'], $name->getLast());
        });
    }
}
```

This will exhaust memory. But removing the specify closure, and just calling the two `assertSame` methods doesn't. Any help on resolving this would be appreciated.

**Comment by tankist** [comment]
Try to add the following code to your _before call:

```
$this->specifyConfig()->shallowClone();
```

**Comment by settermjd** [comment]
Thanks @tankist (interesting Gravatar btw).

**Comment by DavertMik** [comment]
yes, the deep cloning can be a complex thing, while shallow cloning can lead to expected results.
So I'm not sure which way is better. For now deep clone method is default, however you can switch between them

**Comment by settermjd** [comment]
Thanks @DavertMik

**Comment by michaelarnauts** [comment]
@DavertMik is there a reason why this deep cloning is enabled by default? Disabling deep cloning makes a huge difference (> 1 GB memory usage vs 30 Mb)...
