### ISSUE TITLE
Do not display "examples index" when examples are not set

### ISSUE THREAD

**Issue by laland** [Codeception/Specify#29]
Hi! I have some nested specify blocks with no examples set, but i get this output bloated with "examples index 0" stuff:

```
ExtractorTest::tests | extracts package spo | **examples index 0** | extracts agent discount percent | **examples index 0** | when percent is set directly in tour | **examples index 0**
```

Definitely there is a way to show "examples index" only when examples are set.

**Comment by sergeyklay** [comment]
Could you please elaborate?

**Comment by laland** [comment]
For example, let say i have some nested specify blocks like this, which of one fails:
```php
// SomeTest.php
public function tests ()
{
    $this->specify("it does stuff", function() {
        $this->specify("it does another stuff", function() {
            expect(true)->false(); // fails!
        })
    })
}
```
When i run it, i'll get such output telling that test fails:
```
SomeTest::tests | it does stuff | examples index 0 | it does another stuff | examples index 0
... fails for some reason
```

Now the question: is there any way to get rid of "examples index 0" stuff. As you see I have no 'examples' array set in specs, but i getting output like it's set.

**Comment by DavertMik** [comment]
I think it was fixed... In 1.0
