### ISSUE TITLE
Please support php 7.1

### ISSUE THREAD

**Issue by harunnryd** [Codeception/Specify#43]
In ResultPrinter.php line 24:

  Declaration of Codeception\Specify\ResultPrinter::writeProgress($progress): void should be compatible with PHPUnit\TextUI\ResultPrinter::writeProgress(string $progress): void

**Comment by aquamme** [comment]
This is due to incompatible versions of Specify/PHPUnit, not a lack of PHP7 support. Double check that you're using a supported version of PHPUnit with your version of Specify.
