### ISSUE TITLE
Specify does not support PHPUnit 8

### ISSUE THREAD

**Issue by ddinchev** [Codeception/Specify#46]
Although Codeception 3.0 does support it, if you want to keep specify, upgrade to phpunit 8 is still not possible.

**Comment by ruudboon** [comment]
Any updated on this?

**Comment by ddinchev** [comment]
@Naktibalda excuse me for directly bothering you - I see you've recently migrated `codeception/verify` to support PHP8, would you do the same for `/specify`?

**Comment by Naktibalda** [comment]
I wanted to say no, but all I had to do was update composer.json.

Please make a pull request when you want support for PHPUnit 9 next year.

**Comment by Naktibalda** [comment]
I released 1.2.0.
Please test it and raise a new issue if you encounter any problems.

**Comment by ruudboon** [comment]
@Naktibalda Thank you!
