### ISSUE TITLE
Please remove suggesting the use of the assertThrows package

### ISSUE THREAD

**Issue by simonberger** [Codeception/Specify#49]
The assertThrows package is unmaintained. It has a bigger bug open since a long time and no compatibility to PHPUnit 8.
We now remove this package from our tests.

**Comment by Naktibalda** [comment]
Please make a pull request.

**Comment by simonberger** [comment]
In the time I fork and checkout this project the single line is three times removed by a contributor of this project.
If you aren't willing to do so please close this issue.

**Comment by Naktibalda** [comment]
Being unmaintained is not a good reason to remove it from README, codeception/specify is unmaintained either.

**Comment by simonberger** [comment]
What a nice surprise. Thank you for your fielding.

I generally second your statement. But if there are major bugs with a provided fix and incompatibilities to the parent system which both applies to this package without hope for fixes it is a reason to remove in my opinion.
For this specify package I to this point always saw those fixes/changes in a reasonable timeframe.
Anyway you now made it happen for aassert-throws too.
