### ISSUE TITLE
output the specification for report to for detailed tests info

### ISSUE THREAD

**Issue by ghost** [Codeception/Specify#5]
can you add enhancement to this BDD library like when you run 

``` shell
phpunit
```

or 

``` sh
codecept run unit
```

you get the specification (description) of any specify block one by one and the percent of the passed specifications like :

``` sh
username is required ---------------------------- [ X ]
username is too long ---------------------------- [ X ]
username is OK ---------------------------------- [   ]

66 % passed
[===== ===== ===== ===== ===== ===== ===++ +++++ +++++ +++++]

```

**Comment by kniziol** [comment]
Hi. Is it possible nowadays?

**Comment by BarthyB** [comment]
Hey,

I use [this custom trait](https://gist.github.com/BarthyB/a34077f103a9c9d4f0b7909c6bc9b9da) to make tests a little more verbose. 

It's certainly not perfect but does the trick for me.
Feel free use it and suggest changes and/or improvements.

Barthy
