### ISSUE TITLE
recursion error when specifying an anonymous function

### ISSUE THREAD

**Issue by iverberk** [Codeception/Specify#7]
I have this piece of code:

``` PHP
<?php

use Codeception\Specify;

class IntrospectTest extends \Codeception\TestCase\Test
{
    use Specify;

    /**
    * @var \UnitTester
    */
    protected $tester;

    protected function _before()
    {

    }

    protected function _after()
    {
    }

    // tests
    public function testGetColumns()
    {
        $this->specify("this works");

        $this->specify("this doesnt' work", function() {
            return true;
        });
    }

}
```

Seems like the most basic example. When running the suite I get a recursion error on the specify where I define an anonymous function: http://pastebin.com/maXdaJsi . It seems related to the deep copying, but I don't know why as I'm not doing anything special yet. Any suggestions?

**Comment by matperez** [comment]
Hi!

I've got the same issue again. I'm using it with Yii2. The cycle is: Codeception\Lib\Parser -> test\unit\models\OrderFormTest -> Codeception\Lib\Di -> Codeception\Scenario.

My dependencies are:
>      "codeception/codeception": "~2.0@stable",
>      "codeception/specify": "*",
>      "codeception/verify": "*",
>      PHP 5.5.9

What should I do to break the cycle?
